"""Independent numerical audit of Lab 30's finite-window calculation.

Run this file directly; it writes only independent_audit.json beside Lab 30's
existing results. It does not execute Lab 30's main function.

The reference correlation is computed with Python Decimal, independently of
the cubic roots, erfcx, Volterra quadrature, and Mittag-Leffler implementation
used by the audited lab. Expanding the declared Laplace transform at infinity
and inverting each term gives

 C_e(t) = sum_(n,k>=0) (-1)^(n+k) (n/2)_k e^k t^(3n/2+k)
                            / (k! Gamma(1+3n/2+k)).

The n=0 contribution is exactly one. For each n>=1, consecutive k terms have
ratio -e*t*(n/2+k-1)/(k*(3*n/2+k)). Integer and half-integer gamma values are
generated by recurrence, without a floating-point special-function library.

Finite truncation and precision refinements are numerical convergence checks,
not interval enclosures or a proof of accuracy for every admissible input.
The audit is restricted to 0<=epsilon<=0.1 and 0<=t<=50, at the declared cases.
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import platform
import sys
from datetime import datetime, timezone
from decimal import Decimal, localcontext
from pathlib import Path

sys.dont_write_bytecode = True

import numpy as np
import scipy


HERE = Path(__file__).resolve().parent
LAB_PATH = HERE / "30_tempered_memory_boundary.py"
PROTOCOL_PATH = HERE / "tempered_memory_boundary_protocol.json"
OUT = HERE / "results" / "tempered_memory_boundary" / "independent_audit.json"
CASES = [("0", "0.1"), ("0", "11.4"), ("0.001", "1"),
         ("0.001", "11.4"), ("0.1", "1"), ("0.1", "50")]
# More than 100 decimal digits are retained so the precision refinement does
# not reuse an 80-digit approximation to pi.
PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944592307"
    "816406286208998628034825342117067982148086513282306647093844609550"
)
SETTINGS = {
    "baseline": {"precision": 80, "n_max": 160, "k_max": 120},
    "n_refinement": {"precision": 80, "n_max": 240, "k_max": 120},
    "k_refinement": {"precision": 80, "n_max": 240, "k_max": 160},
    "precision_refinement": {"precision": 100, "n_max": 240, "k_max": 160},
}


def sha256(path):
    with Path(path).open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def decimal_correlation(epsilon, time, *, precision, n_max, k_max):
    """Truncated independent series, with inclusive n and k upper limits."""
    eps, t = Decimal(epsilon), Decimal(time)
    if not (Decimal(0) <= eps <= Decimal("0.1") and Decimal(0) <= t <= 50):
        raise ValueError("Audit domain is 0<=epsilon<=0.1 and 0<=t<=50")
    with localcontext() as context:
        context.prec = precision
        gamma_half = {1: PI.sqrt(), 2: Decimal(1)}
        for q in range(3, 3 + 3*n_max):
            gamma_half[q] = (Decimal(q)/2 - 1)*gamma_half[q-2]
        total, power = Decimal(1), Decimal(1)
        t_three_halves = t*t.sqrt()
        for n in range(1, n_max+1):
            power *= -t_three_halves
            term = power/gamma_half[2+3*n]
            subtotal = term
            for k in range(1, k_max+1):
                term *= -eps*t*(Decimal(n)/2+k-1)/(Decimal(k)*(Decimal(3*n)/2+k))
                subtotal += term
            total += subtotal
        return +total


def decimal_difference(left, right):
    with localcontext() as context:
        context.prec = 110
        return abs(left-right)


def main():
    spec = importlib.util.spec_from_file_location("audited_thermal_boundary", LAB_PATH)
    lab = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(lab)
    checks = []

    def check(name, condition, value):
        checks.append({"name": name, "passed": bool(condition), "value": value})

    correlation_rows = []
    for epsilon, time in CASES:
        reference_values = {
            label: decimal_correlation(epsilon, time, **setting)
            for label, setting in SETTINGS.items()
        }
        refined = reference_values["k_refinement"]
        floating = lab.Correlation(float(epsilon))(float(time))
        comparison_error = decimal_difference(Decimal.from_float(floating), refined)
        refinement_errors = {
            "n_refinement": decimal_difference(reference_values["baseline"], reference_values["n_refinement"]),
            "k_refinement": decimal_difference(reference_values["n_refinement"], refined),
            "precision_refinement": decimal_difference(refined, reference_values["precision_refinement"]),
        }
        correlation_rows.append({
            "epsilon_decimal": epsilon, "time_decimal": time,
            "epsilon_float_hex": float(epsilon).hex(), "time_float_hex": float(time).hex(),
            "reference_values": {key: str(value) for key, value in reference_values.items()},
            "lab_correlation": floating,
            "absolute_error_against_80_digit_reference": str(comparison_error),
            "refinement_absolute_differences": {key: str(value) for key, value in refinement_errors.items()},
        })
    max_correlation_error = max(Decimal(row["absolute_error_against_80_digit_reference"])
                                for row in correlation_rows)
    check("six declared correlations versus independent Decimal series",
          max_correlation_error < Decimal("5e-14"), str(max_correlation_error))
    for kind in ("n_refinement", "k_refinement", "precision_refinement"):
        maximum = max(Decimal(row["refinement_absolute_differences"][kind]) for row in correlation_rows)
        check(f"independent series {kind}", maximum < Decimal("1e-50"), str(maximum))

    kl_rows = []
    with localcontext() as context:
        context.prec = 80
        # Both directions are tested because KL is not symmetric.
        examples = [
            ("diagonal alternative to null", np.diag([2., 1.]), np.diag([1., 4.]),
             (Decimal("0.25")+Decimal(2).ln())/2),
            ("diagonal null to alternative", np.diag([1., 4.]), np.diag([2., 1.]),
             (Decimal("2.5")-Decimal(2).ln())/2),
            ("noncommuting covariances alternative to null",
             np.array([[3., .5], [.5, 2.]]), np.array([[2., 1.], [1., 3.]]),
             (Decimal("0.4")+(Decimal(20)/23).ln())/2),
        ]
        for label, alternative, null, expected in examples:
            value, shifts = lab.gaussian_kl(alternative, null)
            error = decimal_difference(Decimal.from_float(value), expected)
            kl_rows.append({"case": label, "alternative_covariance": alternative.tolist(),
                            "null_covariance": null.tolist(), "expected_kl_decimal": str(expected),
                            "computed_kl": value, "absolute_error": str(error),
                            "whitened_covariance_shifts": shifts.tolist()})
    max_kl_error = max(Decimal(row["absolute_error"]) for row in kl_rows)
    check("analytic Gaussian KL direction and noncommuting whitening examples",
          max_kl_error < Decimal("1e-14"), str(max_kl_error))

    remainder_inputs = np.array([-.999, -.5, -1e-4, -1e-8, 0., 1e-8, 1e-4, .5, 10.])
    remainders = lab.stable_log_remainder(remainder_inputs)
    remainder_rows = []
    with localcontext() as context:
        context.prec = 80
        for value, result in zip(remainder_inputs, remainders):
            # Reference the exact binary float supplied to the audited function.
            exact_input = Decimal.from_float(float(value))
            expected = exact_input-(1+exact_input).ln()
            absolute_error = decimal_difference(Decimal.from_float(float(result)), expected)
            relative_error = absolute_error/expected if expected else Decimal(0)
            remainder_rows.append({"input": float(value), "input_float_hex": float(value).hex(),
                                   "expected_decimal": str(expected), "computed": float(result),
                                   "absolute_error": str(absolute_error),
                                   "relative_error": str(relative_error)})
    max_remainder_error = max(Decimal(row["absolute_error"]) for row in remainder_rows)
    tiny_relative_error = max(Decimal(row["relative_error"]) for row in remainder_rows
                              if 0 < abs(row["input"]) < 1e-4)
    check("log remainder versus Decimal evaluation", max_remainder_error < Decimal("1e-14"),
          str(max_remainder_error))
    check("tiny log remainder retains relative precision", tiny_relative_error < Decimal("5e-15"),
          str(tiny_relative_error))
    check("log remainder sign and exact zero", all(row["computed"] > 0 for row in remainder_rows if row["input"] != 0)
          and all(row["computed"] == 0 for row in remainder_rows if row["input"] == 0), True)

    report = {
        "title": "Independent numerical audit of tempered-memory boundary Lab 30",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "status": "Post-implementation numerical audit; not preregistered, an interval certificate, or a proof over the parameter domain.",
        "all_checks_passed": all(row["passed"] for row in checks), "checks": checks,
        "reference_method": "Termwise inverse Laplace series with Decimal arithmetic and integer/half-integer gamma recurrence; no cubic roots or special-function library used in the reference.",
        "settings": SETTINGS, "pi_decimal": str(PI),
        "domain": {"epsilon": [0, 0.1], "time": [0, 50], "scope": "Only the six listed cases are numerically compared."},
        "correlation_cases": correlation_rows, "gaussian_kl_cases": kl_rows,
        "log_remainder_cases": remainder_rows,
        "limitations": [
            "Convergence under finite truncation and precision changes is evidence, not a rigorous error enclosure.",
            "The reference and lab evaluate the same declared analytic model, so this does not validate that model against experimental data.",
            "Decimal reference parameters use the listed decimal values; the lab receives their nearest binary floating-point representations.",
            "The KL checks verify the numerical formula. The independence assumptions and Pinsker interpretation require the accompanying mathematical argument.",
            "This audit imports Lab 30 without executing its main function or modifying its results."
        ],
        "hashes": {"audit_script": sha256(__file__), "audited_lab_script": sha256(LAB_PATH),
                   "audited_lab_protocol": sha256(PROTOCOL_PATH)},
        "environment": {"python": platform.python_version(), "decimal": "Python standard library",
                        "numpy": np.__version__, "scipy": scipy.__version__},
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2, allow_nan=False)+"\n", encoding="utf-8")
    print(json.dumps({"all_checks_passed": report["all_checks_passed"], "checks": checks,
                      "output": str(OUT)}, indent=2, allow_nan=False))
    if not report["all_checks_passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
